package cat.rubenzu03.catbrary.api

internal data class BreedRatings(
    val adaptability: Int,
    val affectionLevel: Int,
    val childFriendly: Int,
    val dogFriendly: Int,
    val energyLevel: Int,
    val grooming: Int,
    val healthIssues: Int,
    val intelligence: Int,
    val sheddingLevel: Int,
    val socialNeeds: Int,
    val strangerFriendly: Int,
)

internal val HISTORICAL_BREED_RATINGS: Map<String, BreedRatings> =
    mapOf(
        "abob" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 3),
        "abys" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 3, dogFriendly = 4, energyLevel = 5, grooming = 1, healthIssues = 2, intelligence = 5, sheddingLevel = 2, socialNeeds = 5, strangerFriendly = 5),
        "acur" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 2, healthIssues = 1, intelligence = 3, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 3),
        "aege" to BreedRatings(adaptability = 5, affectionLevel = 4, childFriendly = 4, dogFriendly = 4, energyLevel = 3, grooming = 3, healthIssues = 1, intelligence = 3, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 4),
        "amau" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 1, healthIssues = 1, intelligence = 3, sheddingLevel = 1, socialNeeds = 3, strangerFriendly = 3),
        "amis" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 3, healthIssues = 1, intelligence = 4, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 4),
        "asho" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 1, healthIssues = 3, intelligence = 3, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 3),
        "awir" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 1, healthIssues = 3, intelligence = 3, sheddingLevel = 1, socialNeeds = 3, strangerFriendly = 3),
        "bali" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 3, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "bamb" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 1, socialNeeds = 3, strangerFriendly = 3),
        "beng" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 3),
        "birm" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 2, healthIssues = 1, intelligence = 3, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 3),
        "bomb" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 1, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 4),
        "bsho" to BreedRatings(adaptability = 5, affectionLevel = 4, childFriendly = 4, dogFriendly = 5, energyLevel = 2, grooming = 2, healthIssues = 2, intelligence = 3, sheddingLevel = 4, socialNeeds = 3, strangerFriendly = 2),
        "bslo" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 5, healthIssues = 1, intelligence = 5, sheddingLevel = 1, socialNeeds = 3, strangerFriendly = 4),
        "bure" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 1, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "buri" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 4, energyLevel = 3, grooming = 3, healthIssues = 3, intelligence = 3, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 3),
        "char" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 2, grooming = 1, healthIssues = 2, intelligence = 4, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "chau" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 3, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 4),
        "chee" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 1, socialNeeds = 3, strangerFriendly = 4),
        "crex" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 2, intelligence = 5, sheddingLevel = 1, socialNeeds = 5, strangerFriendly = 3),
        "csho" to BreedRatings(adaptability = 3, affectionLevel = 4, childFriendly = 4, dogFriendly = 4, energyLevel = 4, grooming = 2, healthIssues = 2, intelligence = 5, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 2),
        "cspa" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 1, socialNeeds = 3, strangerFriendly = 4),
        "ctif" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 5, healthIssues = 1, intelligence = 5, sheddingLevel = 5, socialNeeds = 3, strangerFriendly = 4),
        "cymr" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 3, healthIssues = 3, intelligence = 5, sheddingLevel = 5, socialNeeds = 5, strangerFriendly = 3),
        "cypr" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 3, healthIssues = 1, intelligence = 3, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 4),
        "dons" to BreedRatings(adaptability = 4, affectionLevel = 4, childFriendly = 3, dogFriendly = 3, energyLevel = 4, grooming = 2, healthIssues = 3, intelligence = 3, sheddingLevel = 1, socialNeeds = 5, strangerFriendly = 5),
        "drex" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 3, intelligence = 5, sheddingLevel = 1, socialNeeds = 5, strangerFriendly = 5),
        "ebur" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 4, energyLevel = 4, grooming = 1, healthIssues = 4, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "emau" to BreedRatings(adaptability = 2, affectionLevel = 5, childFriendly = 3, dogFriendly = 3, energyLevel = 5, grooming = 1, healthIssues = 3, intelligence = 4, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 2),
        "esho" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 3, dogFriendly = 3, energyLevel = 3, grooming = 2, healthIssues = 3, intelligence = 3, sheddingLevel = 2, socialNeeds = 4, strangerFriendly = 2),
        "hbro" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 3),
        "hima" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 2, dogFriendly = 2, energyLevel = 1, grooming = 5, healthIssues = 3, intelligence = 3, sheddingLevel = 4, socialNeeds = 4, strangerFriendly = 2),
        "java" to BreedRatings(adaptability = 4, affectionLevel = 5, childFriendly = 4, dogFriendly = 4, energyLevel = 5, grooming = 1, healthIssues = 3, intelligence = 5, sheddingLevel = 2, socialNeeds = 5, strangerFriendly = 3),
        "jbob" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "khao" to BreedRatings(adaptability = 4, affectionLevel = 4, childFriendly = 3, dogFriendly = 3, energyLevel = 3, grooming = 3, healthIssues = 1, intelligence = 4, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 3),
        "kora" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 2),
        "kuri" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 5, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 2, socialNeeds = 5, strangerFriendly = 5),
        "lape" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 4),
        "lihu" to BreedRatings(adaptability = 3, affectionLevel = 3, childFriendly = 3, dogFriendly = 3, energyLevel = 3, grooming = 1, healthIssues = 1, intelligence = 3, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 3),
        "mala" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 3, sheddingLevel = 1, socialNeeds = 3, strangerFriendly = 3),
        "manx" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 3, intelligence = 5, sheddingLevel = 5, socialNeeds = 5, strangerFriendly = 3),
        "mcoo" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 3, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 5),
        "munc" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 2, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "nebe" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 4, energyLevel = 3, grooming = 3, healthIssues = 2, intelligence = 5, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 3),
        "norw" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 2, healthIssues = 3, intelligence = 4, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "ocic" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "orie" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 3),
        "pers" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 2, dogFriendly = 2, energyLevel = 1, grooming = 5, healthIssues = 3, intelligence = 3, sheddingLevel = 4, socialNeeds = 4, strangerFriendly = 2),
        "pixi" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 1, healthIssues = 2, intelligence = 5, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 4),
        "raga" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 3, healthIssues = 3, intelligence = 5, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 5),
        "ragd" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 2, healthIssues = 3, intelligence = 3, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 3),
        "rblu" to BreedRatings(adaptability = 3, affectionLevel = 3, childFriendly = 3, dogFriendly = 3, energyLevel = 3, grooming = 3, healthIssues = 1, intelligence = 3, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 1),
        "sava" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "sfol" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 1, healthIssues = 4, intelligence = 3, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 3),
        "siam" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 2, socialNeeds = 5, strangerFriendly = 5),
        "sibe" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 2, healthIssues = 2, intelligence = 5, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 3),
        "sing" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "snow" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 4, grooming = 3, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 4),
        "soma" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 3, dogFriendly = 4, energyLevel = 5, grooming = 3, healthIssues = 2, intelligence = 5, sheddingLevel = 4, socialNeeds = 5, strangerFriendly = 5),
        "sphy" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 2, healthIssues = 4, intelligence = 5, sheddingLevel = 1, socialNeeds = 5, strangerFriendly = 5),
        "srex" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 3, grooming = 2, healthIssues = 4, intelligence = 3, sheddingLevel = 1, socialNeeds = 3, strangerFriendly = 3),
        "tang" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 2, healthIssues = 2, intelligence = 5, sheddingLevel = 2, socialNeeds = 5, strangerFriendly = 5),
        "tonk" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 5, strangerFriendly = 5),
        "toyg" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 1, healthIssues = 2, intelligence = 5, sheddingLevel = 3, socialNeeds = 3, strangerFriendly = 5),
        "tvan" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 2, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 4),
        "ycho" to BreedRatings(adaptability = 5, affectionLevel = 5, childFriendly = 4, dogFriendly = 5, energyLevel = 5, grooming = 3, healthIssues = 1, intelligence = 5, sheddingLevel = 3, socialNeeds = 4, strangerFriendly = 4),
    )
